Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : André Rodrigues
// Descrição   : Desenvolver um código de Armazenamento de Dados .alg
// Autor(a)    : Alisson, Amilton, Davi, Gabriel A., Gabriel V., Lucas
// Data atual  : 02/06/2020
Var
    // Seção de Declarações das variáveis 

    // Fim Seção de Declarações das variáveis

Inicio
    // Seção de Comandos

    // Fim Seção de Comandos
Fimalgoritmo